name: d100_d300_env
channels:
  - conda-forge
dependencies:
  - python=3.11.*
  - ucimlrepo=0.0.*
  - numpy=1.26.*
  - pandas=2.2.*
  - pyarrow=19.*
  - matplotlib=3.10.*
  - seaborn=0.13.*
  - polars=1.30.*
  - scikit-learn=1.6.*
  - lightgbm=4.*
  - scipy=1.*
  - joblib=1.*
  - jupyter=1.*
  - pip:
    - pre-commit==3.4.0
