name: d100_d400_env
channels:
  - conda-forge
dependencies:
  - python=3.12.12
  - ucimlrepo=0.0.7
  - numpy=2.3.5
  - pandas=2.2.3
  - pyarrow=21.0.0
  - matplotlib=3.10.7
  - seaborn=0.13.2
  - polars=1.34.0
  - scikit-learn=1.7.2
  - lightgbm=4.6.0
  - scipy=1.16.3
  - joblib=1.5.2
  - jupyter=1.1.1
  - pip:
    - pre-commit==3.4.0
    - pytest==7.0
    - black==23.9.1
    - mypy==1.3.0
    - flake8==6.1.0
    - isort==5.12.0
    - build==1.3.0
    - twine==6.2.0
