[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "income_predict"
version = "0.1.0"
description = "My installable package for income prediction"
requires-python = ">=3.9"
dependencies = []

[tool.setuptools.packages.find]
where = ["src"]